spring:
  application:
    name: wsecommerce
  profiles:
    active: dev # dev qa ... prod
  config:
    import: "configserver:http://3.80.118.11:8888"
  # Asegurar que Spring preste atención a los recursos estáticos internos
  web:
    resources:
      add-mappings: true
